### ISSUE TITLE
Crash when trying to log in

### ISSUE THREAD

**Issue by tealshift** [back4app/parse-cli-server#28]
When I try to log in, I get this output:
`Got error: parse: error with status=500 and body="TypeError: _errors2.default is not a constructor<br> &nbsp; &nbsp;at /home/back4app/scm/back4app-cli-server/lib/back/Back4appVendorAdapter.js:341:19<br> &nbsp; &nbsp;at tryCatcher (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/util.js:16:23)<br> &nbsp; &nbsp;at Promise._settlePromiseFromHandler (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:510:31)<br> &nbsp; &nbsp;at Promise._settlePromise (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:567:18)<br> &nbsp; &nbsp;at Promise._settlePromise0 (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:612:10)<br> &nbsp; &nbsp;at Promise._settlePromises (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:691:18)<br> &nbsp; &nbsp;at Async._drainQueue (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/async.js:133:16)<br> &nbsp; &nbsp;at Async._drainQueues (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/async.js:143:10)<br> &nbsp; &nbsp;at Immediate.Async.drainQueues (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/async.js:17:14)<br> &nbsp; &nbsp;at runCallback (timers.js:637:20)<br> &nbsp; &nbsp;at tryOnImmediate (timers.js:610:5)<br> &nbsp; &nbsp;at processImmediate [as _immediateCallback] (timers.js:582:5)\n"parse: error with status=500 and body="TypeError: _errors2.default is not a constructor<br> &nbsp; &nbsp;at /home/back4app/scm/back4app-cli-server/lib/back/Back4appVendorAdapter.js:341:19<br> &nbsp; &nbsp;at tryCatcher (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/util.js:16:23)<br> &nbsp; &nbsp;at Promise._settlePromiseFromHandler (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:510:31)<br> &nbsp; &nbsp;at Promise._settlePromise (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:567:18)<br> &nbsp; &nbsp;at Promise._settlePromise0 (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:612:10)<br> &nbsp; &nbsp;at Promise._settlePromises (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/promise.js:691:18)<br> &nbsp; &nbsp;at Async._drainQueue (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/async.js:133:16)<br> &nbsp; &nbsp;at Async._drainQueues (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/async.js:143:10)<br> &nbsp; &nbsp;at Immediate.Async.drainQueues (/home/back4app/scm/back4app-cli-server/node_modules/bluebird/js/release/async.js:17:14)<br> &nbsp; &nbsp;at runCallback (timers.js:637:20)<br> &nbsp; &nbsp;at tryOnImmediate (timers.js:610:5)<br> &nbsp; &nbsp;at processImmediate [as _immediateCallback] (timers.js:582:5)\n"`

**Comment by tealshift** [comment]
Ah, looks like this was caused by my account key expiring. Hope this helps. It's really bad that it doesn't properly report the expiration.
